server {
    listen 80;
    root /usr/share/nginx/html;
    autoindex on;               # インストーラは /kinoite/ 配下をディレクトリとして辿る
    types { application/octet-stream iso img; text/plain ks cfg; }
    location / { try_files $uri $uri/ =404; }
}
